spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  datasource:
      driver-class-apartmentName: com.mysql.jdbc.Driver   #mysql的驱动
      url: jdbc:mysql://127.0.0.1:3306/iof?serverTimezone=UTC   #有时若不设置时区将报错
      username: root
      password: root

mybatis:
  typeAliasesPackage: com.itmsw.entity
  mapperLocations: classpath:mapper/*.xml


server:
  servlet:
    context-path: /iof
  port: 8095
#  port: 443
#  ssl:
#      key-store: C:\Program Files\Apache Software Foundation\Tomcat 7.0\conf\cert\1525688816500.pfx
#      key-store-password: 1525688816500
#      keyStoreType: PKCS12